### ISSUE TITLE
A few suggestions for the network

### ISSUE THREAD

**Issue by sjmiller609** [spotinst/terraform-spotinst-ocean-eks#13]
You probably ought to have VPC layout larger than /24 per subnet by default.
Also, you probably do not want single NAT gateway by default.

**Comment by sjmiller609** [comment]
In my experience, I have preferred

254 hosts each public network subnet

public_subnets = ["10.3.0.0/24", "10.3.1.0/24", "10.3.2.0/24"]

16382 hosts each private network

private_subnets = ["10.3.64.0/18", "10.3.128.0/18", "10.3.192.0/18"]

This could help your customers avoid running out of IP space when they have a lot of Pods. I ran into this issue at Astronomer, where we used Spot https://github.com/astronomer/terraform-aws-astronomer-aws/blob/3655bb7dcc746a7848c2d52fb5992ebbe01bb61f/vpc.tf#L19 

Below, ignore black box. But this is how a 10.3.0.0/16 could be chunked to have three very large /18 networks for kubernetes.

![image](https://user-images.githubusercontent.com/7516283/125862872-adceeddf-0472-4384-ab58-d113cae8217b.png)

**Comment by liranp** [comment]
Thank you for your suggestions, @sjmiller609. I've [exposed](https://github.com/spotinst/terraform-spotinst-ocean-eks/commit/4595224b52229d50d1238546277ebf71210e7e80#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288eR383-R399) those variables and kept their current values to maintain backward compatibility, but you can now override them as needed. Release [v1.4.0](https://registry.terraform.io/modules/spotinst/ocean-eks/spotinst/1.4.0) is available now. I hope you're okay with that.
