### ISSUE TITLE
Feature to configure autoscaler block and attributes for spotinst-ocean-eks

### ISSUE THREAD

**Issue by bharatgovindaradjou** [spotinst/terraform-spotinst-ocean-eks#18]
Currently ocean-eks module defaults autoscaler configuration to automatic configuration when enabled. The autoscaler is also [enabled by default.](https://github.com/spotinst/terraform-spotinst-ocean-eks/blob/master/ocean.tf#L42,43)

```
autoscaler {
    autoscale_is_enabled     = true
    autoscale_is_auto_config = true
  }
}
```

The purpose of this issue is to add some flexibility to spotinst/ocean-eks module to make use of the ability to configure autoscaler available in the **spotinst_ocean_aws** resource.

This gives us infrastructure designers and engineers using spotinst to develop ocean clusters configurable for autoscalers' headroom, cooldown and resource limits and even pass on values to ocean's virtual node groups

```
autoscaler {
  autoscale_is_enabled     = true
  autoscale_is_auto_config = true
  auto_headroom_percentage = 100
  autoscale_cooldown       = 300

  autoscale_headroom {
    cpu_per_unit    = 1024
    gpu_per_unit    = 0
    memory_per_unit = 512
    num_of_units    = 2
  }

  autoscale_down {
    max_scale_down_percentage = 60
  }

  resource_limits {
    max_vcpu       = 1024
    max_memory_gib = 1500
  }
}
```

**Comment by liranp** [comment]
Merged #19.
