### ISSUE TITLE
VPC module version

### ISSUE THREAD

**Issue by riveroso** [spotinst/terraform-spotinst-ocean-eks#31]
There is a new v4 release of the vpc module (terraform-aws-modules/vpc/aws) that depends on eks provider >= 4.35, and generates a conflict. Please set the version as `version = ">= 2.78.0, < 4.0.0"` on the vpc.tf file.

**Comment by jmrs-22** [comment]
Hi there. Did you manage to solve the problem? I've struggling with it for the last two days but no luck.

**Comment by riveroso** [comment]
This module has been deprecated. They updated the README file with info about that.

**Comment by riveroso** [comment]
This module has been deprecated.
