### ISSUE TITLE
terraform >0.12 support

### ISSUE THREAD

**Issue by lucheeseng827** [spotinst/terraform-spotinst-ocean-eks#5]
Hi there, I woud like to know if there is any workaround to get it running on Terraform 0.13 onward?

**Comment by liranp** [comment]
[Released v0.6.0](https://registry.terraform.io/modules/spotinst/ocean-eks/spotinst/0.6.0) (https://github.com/spotinst/terraform-spotinst-ocean-eks/commit/70a0b605f5a080e253b7faf06fdae42bb5911ff8).
