### ISSUE TITLE
Terraform kubernetes provider update has removed argument

### ISSUE THREAD

**Issue by apaterson-ecs** [spotinst/terraform-spotinst-ocean-eks#6]
Terraform kubernetes provider v2.0.0 has been release and they have removed the following argument:
load_config_file
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-to-kubernetes-credentials-supplied-in-the-provider-block

This is specified in ocean.tf file on line 7 and needs to be removed if people are using latest kubernetes version (> v2.0.0)
There is no way to set the kubernetes version in the variables.tf file.

**Comment by liranp** [comment]
[Fixed](https://github.com/spotinst/terraform-spotinst-ocean-eks/commit/c24680143ded63898c78871fc0549f455fa56b28) and [released](https://registry.terraform.io/modules/spotinst/ocean-eks/spotinst/0.5.0). Thanks!
