### ISSUE TITLE
Adding controller_image and image_pull_policy variables for ocean-controller 0.18.0

### ISSUE THREAD

**Issue by jonjemstep** [spotinst/terraform-spotinst-ocean-eks#8]
We need to make use of the two variables to get around the unauthenticated DockerHub Pull limits when making use of the module. 

The module was updated recently please see:
https://registry.terraform.io/modules/spotinst/ocean-controller/spotinst/latest

However the ocean.tf does not make use of those variables meaning we cannot make use of the latest version, the use of the module can be seen here:
https://github.com/Intelliflo/terraform-config-eks/blob/ocean-tf/main.tf

We have a PR with the necessary changes:
https://github.com/spotinst/terraform-spotinst-ocean-eks/pull/7

**Comment by liranp** [comment]
Released [v0.7.0](https://registry.terraform.io/modules/spotinst/ocean-eks/spotinst/0.7.0).
